### ISSUE TITLE
Need some handholding

### ISSUE THREAD

**Issue by ovizii** [reisbel/guacamole-docker-compose#1]
Hi there,

I tried adapting your dockerfile so that guacamole runs behind traefik and saves the DB persistent into a volume but what happens is that I see the tomcat default page, see screenshot: https://pasteboard.co/IncUTPv.png 

Here is my adapted dockerfile: https://pastebin.com/jfHzS7Bk 
my changes are lines # 15, 29, 30, 40, 41, 42, 43

Any idea what I am doing wrong?

**Comment by JenswBE** [comment]
Hi Ovizzi,

Your config seems good. I assume you just have to use following path to connect: `https://my.domain.tld/guacamole`.

In case you want to remove the prefix, you can use following label:
` - "traefik.frontend.rule=Host:my.domain.tld; AddPrefix: /guacamole"`

You can check [my personal docker-compose](https://github.com/JenswBE/wolverine/blob/master/docker-compose.yml) for a fully working example, including Traefik (based on this repo).

**Comment by ovizii** [comment]
*facepalm*
you're right, I was missing the trailing guacamole.

Thanks for the traefik pointer with the AddPrefix and sharing your personal docker-compose file which has a lot of useful tips for me like how to connect the traefik network to the guacamole one :-)
